In [1]:
import numpy as np

Задание 1

In [2]:
arr=np.array([[1, 2, 3, 3, 1],
              [6, 8, 11, 10, 7]])

In [3]:
np.mean(arr, axis=1)

array([2. , 8.4])

Задание 2

In [4]:
import numpy as np

Задание 1

In [5]:
arr=np.transpose(np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]]))

In [6]:
mean_a=np.mean(arr, axis=0)

Проверяю требуемую размерость исходной матрицы (5 строк на два столбца) и полученный результат (вручную. средние 2 и 8,4

In [7]:
np.shape(arr)

(5, 2)

In [8]:
mean_a

array([2. , 8.4])

Задание 2

In [9]:
a_centered=arr-mean_a

Проверяю полученный массив (размер 5х2)

In [12]:
a_centered
print(f'размерность:{np.shape(a_centered)[0]}x{np.shape(a_centered)[1]}')

размерность:5x2


In [13]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [14]:
a_centered_sp=a_centered[0, 0]*a_centered[1, 0]+a_centered[1, 0]*a_centered[1, 1]+a_centered[2, 0]*a_centered[2, 1]+a_centered[3, 0]*a_centered[3, 1]+a_centered[4, 0]*a_centered[4, 1]
dispersion=a_centered_sp/(np.shape(a_centered)[0]-1)

Задание 4

In [15]:
print(f'Значение ковариации соответствует: {np.cov(np.transpose(arr))[0, 1]}')

Значение ковариации соответствует: 2.0


ДОМАШНЯЯ РАБОТА 2

Задание 1

In [1]:
import pandas as pd

In [2]:
authors=pd.DataFrame({'author_id':[1, 2, 3], 'author_name':['Тургеньев', 'Чехов', "Островский"]}, columns=['author_id', 'author_name'])
books=pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3], 'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Поклонники'], 'price':[450, 300, 350, 500, 450, 370, 290]})

Задание 2

In [3]:
authors_price=pd.merge(authors, books, on='author_id', how='outer')
authors_price

author_id author_name         book_title  price
0          1   Тургеньев        Отцы и дети    450
1          1   Тургеньев              Рудин    300
2          1   Тургеньев  Дворянское гнездо    350
3          2       Чехов   Толстый и тонкий    500
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
6          3  Островский         Поклонники    290

Задание 3

In [20]:
top5=authors_price.sort_values(by='price', ascending=False).head(5)
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1   Тургеньев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1   Тургеньев  Дворянское гнездо    350

In [21]:
### при попытке включить в код .reset_index() выдает исключение ValueError с комментарием ValueError: cannot insert level_0, already exists

Задание 4

In [33]:
authors_stat=authors_price.groupby('author_name').agg({'price' : ['min', 'max', 'mean']})
authors_stat

price                 
              min  max        mean
author_name                       
Островский    290  370  330.000000
Тургеньев     300  450  366.666667
Чехов         450  500  475.000000