In [1]:
import numpy as np

In [2]:
X1=np.array([[1, 2],
             [3, 4],
             [5, 6]])
X2=np.array([[7, 6, 8],
             [9, 10, 11]])
X1.shape, X2.shape

((3, 2), (2, 3))

In [4]:
X1.shape[0], X2.shape[1]

(3, 3)

In [5]:
X1.shape[0]==X2.shape[1]

True

In [7]:
np.dot(X1, X2)

array([[ 25,  26,  30],
       [ 57,  58,  68],
       [ 89,  90, 106]])

In [8]:
X2=([[7, 8, 9, 10],
     [11, 12, 13, 14]])

In [9]:
Z=np.dot(X1, X2)
Z

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

In [10]:
Z.shape
Z

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

In [11]:
Z.shape

(3, 4)

In [12]:
A_square=np.linalg.matrix_power(A, 2)

NameError: name 'A' is not defined

In [13]:
A=np.array([[0, 1, 2],
            [3, 4, 5],
            [6, 7 ,8]])
A_square=np.linalg.matrix_power(A, 2)

In [14]:
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [15]:
np.dot(A, A)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [16]:
I-np.eye(3)
I

NameError: name 'I' is not defined

In [17]:
I=np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
X1t=X.trancepose()

NameError: name 'X' is not defined

In [19]:
X1t=X1.trancepose()

AttributeError: 'numpy.ndarray' object has no attribute 'trancepose'

In [20]:
X1t=X1.trancpose()

AttributeError: 'numpy.ndarray' object has no attribute 'trancpose'

In [23]:
X1t=X1.transpose()

In [24]:
X1t

array([[1, 3, 5],
       [2, 4, 6]])

In [25]:
X1t.T

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
np.linalg.det(eye)

NameError: name 'eye' is not defined

In [27]:
np.linalg(I)

TypeError: 'module' object is not callable

In [28]:
A=array([[0, 1, 2],
         [4, 5, 6],
         [7, 8, 9]])
np.linalg.det(A)

NameError: name 'array' is not defined

In [29]:
A=np.array([[0, 1, 2],
         [4, 5, 6],
         [7, 8, 9]])
np.linalg.det(A)

-1.554312234475226e-15

In [30]:
np.linalg.matrix_rank(A)

2

In [31]:
%%time
np.linalg.matrix_rank(A)

Wall time: 1.02 ms


2

In [33]:
%%time
A_inv=np.linalg.inv(A)

Wall time: 0 ns


In [34]:
A_inv

array([[ 1.93011413e+15, -4.50359963e+15,  2.57348550e+15],
       [-3.86022825e+15,  9.00719925e+15, -5.14697100e+15],
       [ 1.93011413e+15, -4.50359963e+15,  2.57348550e+15]])

In [35]:
a=np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
a.ones((3, 4))
a

AttributeError: 'numpy.ndarray' object has no attribute 'ones'

In [37]:
a=np.ones((3, 4))

In [38]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
full=np.array([[np.arange(10)], [np.arange(11, 20)], [np.arange(21, 30)]])
full

<ipython-input-40-17eb314c99d6>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  full=np.array([[np.arange(10)], [np.arange(11, 20)], [np.arange(21, 30)]])


array([[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])],
       [array([11, 12, 13, 14, 15, 16, 17, 18, 19])],
       [array([21, 22, 23, 24, 25, 26, 27, 28, 29])]], dtype=object)

In [41]:
full=np.array([[np.arange(1, 10)], [np.arange(11, 20)], [np.arange(21, 30)]])
full

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9]],

       [[11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[21, 22, 23, 24, 25, 26, 27, 28, 29]]])

In [42]:
full=np.array([np.arange(10), np.arange(11, 20), np.arange(21, 30)])
full

<ipython-input-42-5c20a2270c67>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  full=np.array([np.arange(10), np.arange(11, 20), np.arange(21, 30)])


array([array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
       array([11, 12, 13, 14, 15, 16, 17, 18, 19]),
       array([21, 22, 23, 24, 25, 26, 27, 28, 29])], dtype=object)

In [43]:
full=np.array([np.arange(1, 10), np.arange(11, 20), np.arange(21, 30)])
full

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [44]:
np.random.sample()

0.26850356829071864

In [45]:
np.random.sample(1, 5)

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [46]:
np.random.sample((1, 5))

array([[0.51193679, 0.46551605, 0.1433603 , 0.02189246, 0.99732866]])

In [47]:
for each in (np.random.sample((1, 5))):
    print(f'{each}\n')

[0.93241519 0.62260077 0.75437678 0.65092784 0.58755143]



In [48]:
for each in (np.random.sample((1, 5))):
    print(f'{each}\n', end='\n')

[0.74380724 0.72528698 0.90894978 0.87552091 0.09019876]



In [49]:
for each in (np.random.sample((1, 5))):
    print(f'{each}\n', end='тут конец строки')

[0.5610852  0.45013602 0.81180319 0.77695893 0.12578021]
тут конец строки

In [50]:
np.random.randint(-2, 5, 10)

array([ 2, -2,  4,  4,  0, -1,  3,  2,  1,  0])

In [51]:
average(np.random.randint(-2, 5, 10))

NameError: name 'average' is not defined

In [52]:
p=np.random.randint(-2, 5, 10)

In [53]:
average=sum(p)/len(p)
average

1.2

In [54]:
%%time
np.random.randint(0, 10, (3, 4))

Wall time: 0 ns


array([[2, 6, 2, 0],
       [4, 1, 8, 5],
       [7, 7, 9, 1]])

In [55]:
np.random.choice(p, 4)
p

array([-2,  2,  0,  1,  4,  3,  1,  1,  2,  0])

In [56]:
np.random.choice(p, 4)

array([ 1,  0,  3, -2])

In [57]:
re_p=np.reshape(3, 4)

ValueError: cannot reshape array of size 1 into shape (4,)

In [58]:
re_p=p.np.reshape(3, 4)

AttributeError: 'numpy.ndarray' object has no attribute 'np'

In [59]:
re_p=p.reshape(3, 4)
re_p

ValueError: cannot reshape array of size 10 into shape (3,4)

In [60]:
re_p=np.reshape(1, 10)

ValueError: cannot reshape array of size 1 into shape (10,)

In [61]:
p

array([-2,  2,  0,  1,  4,  3,  1,  1,  2,  0])

In [62]:
re_p=np.reshape(2, 5)

ValueError: cannot reshape array of size 1 into shape (5,)

In [63]:
re_p=np.reshape(1, 4)

ValueError: cannot reshape array of size 1 into shape (4,)

In [64]:
re_p=np.reshape(3, 2)

ValueError: cannot reshape array of size 1 into shape (2,)

In [65]:
re_p=np.reshape(3, -1)

In [66]:
re_p

array([3])

In [67]:
re_p=p.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)

In [1]:
mean?

Object `mean` not found.


In [2]:
np.mean?

Object `np.mean` not found.
