In [1]:
import numpy as np

Задание 1

In [2]:
arr=np.array([[1, 2, 3, 3, 1],
              [6, 8, 11, 10, 7]])

In [3]:
np.mean(arr, axis=1)

array([2. , 8.4])

Задание 2

In [4]:
import numpy as np

Задание 1

In [5]:
arr=np.transpose(np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]]))

In [6]:
mean_a=np.mean(arr, axis=0)

Проверяю требуемую размерость исходной матрицы (5 строк на два столбца) и полученный результат (вручную. средние 2 и 8,4

In [7]:
np.shape(arr)

(5, 2)

In [8]:
mean_a

array([2. , 8.4])

Задание 2

In [9]:
a_centered=arr-mean_a

Проверяю полученный массив (размер 5х2)

In [12]:
a_centered
print(f'размерность:{np.shape(a_centered)[0]}x{np.shape(a_centered)[1]}')

размерность:5x2


In [13]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [14]:
a_centered_sp=a_centered[0, 0]*a_centered[1, 0]+a_centered[1, 0]*a_centered[1, 1]+a_centered[2, 0]*a_centered[2, 1]+a_centered[3, 0]*a_centered[3, 1]+a_centered[4, 0]*a_centered[4, 1]
dispersion=a_centered_sp/(np.shape(a_centered)[0]-1)

Задание 4

In [15]:
print(f'Значение ковариации соответствует: {np.cov(np.transpose(arr))[0, 1]}')

Значение ковариации соответствует: 2.0
